-- Experience Review Platform - Database Schema
-- PostgreSQL. This file is a reference only.
--
-- For applying schema, use the split scripts in docs/schema/ in order:
--   001_create_category_table.sql
--   002_create_subcategory_table.sql
--   003_create_products_table.sql
--   004_create_users_table.sql
--   005_create_reviews_table.sql
--   006_insert_mock_categories.sql
--   007_insert_mock_subcategories.sql
--   008_insert_mock_products.sql
--
-- See docs/schema/README.md for run order and usage.
